{
  imports = [
    ./languages
    ./autopairs.nix
    ./comment.nix
    ./completion.nix
    ./conform.nix
    ./diffview.nix
    ./dressing.nix
    ./gitsigns.nix
    ./lazygit.nix
    ./lint.nix
    ./lsp.nix
    ./lspkind.nix
    ./lualine.nix
    ./lualine.nix
    ./luasnip.nix
    ./mini.nix
    ./oil.nix
    ./telescope.nix
    ./tmux.nix
    ./treesitter.nix
    ./web-devicons.nix
  ];
}
