{
  imports = [
    ./languages
    ./autopairs.nix
    ./blink.nix
    ./codecompanion.nix
    ./comment.nix
    ./fugitive.nix
    ./gitsigns.nix
    ./lint.nix
    ./lsp.nix
    ./lsp-format.nix
    ./lualine.nix
    ./luasnip.nix
    ./mini.nix
    ./oil.nix
    ./snacks
    ./toggleterm
    ./treesitter.nix
    ./web-devicons.nix
  ];
}
